services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydatabase
      REDIS_URL: redis://redis:6379
      GOOGLE_CLIENT_ID: 52389663784289457943875jkdsfhkh
      JWT_SECRET: abcdefgh

    develop:
      watch:
        - action: sync
          path: ./backend
          target: ./backend/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_GOOGLE_CLIENT_ID: 523896637842-m7aigfsdfhlskjhfdksjdhfkjsh
      REACT_APP_BACK_END_URL: http://localhost:4000/graphql
      REACT_APP_BACK_END_WS: ws://localhost:4000/graphql
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: ./frontenc/src/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - postgres
      - redis
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
