version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydatabase
      REDIS_URL: redis://redis:6379
      GOOGLE_CLIENT_ID: 52389663784289457943875jkdsfhkh
      JWT_SECRET: 0edf14a7bb56381a221e26b291cf65d3

    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_GOOGLE_CLIENT_ID: 523896637842-m7aigfsdfhlskjhfdksjdhfkjsh
      REACT_APP_BACK_END_URL: http://localhost:4000/graphql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - postgres
      - redis
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
